# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='dimension',
            field=models.IntegerField(default=2),
        ),
    ]
