# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_shape_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='number1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='number2',
            field=models.FloatField(default=0),
        ),
    ]
