# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20160511_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='measurement',
            field=models.CharField(default='area', max_length=35),
        ),
    ]
