# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_shape_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='number3',
            field=models.FloatField(default=0),
        ),
    ]
